# encoding: utf-8
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['musicbar/__init__.py']
APP_NAME = 'musicbar'
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': 'Now-playing songs in your menubar',
        'CFBundleIdentifier': "co.sgfc.musicbar",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2019 russelg, All Rights Reserved",
        'LSUIElement': True,
    },
    'packages': ['rumps', 'musicbar', 'applescript'],
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
